# Generated by Django 5.2.3 on 2025-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=50)),
                ('Stu_city', models.CharField(max_length=50)),
                ('Stu_email', models.EmailField(max_length=254)),
                ('Stu_contact', models.IntegerField()),
                ('Stu_image', models.ImageField(upload_to='image/')),
                ('Stu_doc', models.ImageField(upload_to='doc/')),
            ],
        ),
    ]
