# Generated by Django 5.2.3 on 2025-06-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5th', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Stu_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_doc',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_name',
            new_name='name',
        ),
    ]
